org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
app.version.code=10
app.version.name=1.2.0
app.version.suffix=


android.useFullClasspathForDexingTransform=true
android.enableJetifier=true
android.defaults.buildfeatures.buildconfig=true
android.nonFinalResIds=false

app.signing.keyAlias=mizan_r
app.signing.keyPassword=Miz@n&&%%$$0801
app.signing.storePassword=Miz@n&&%%$$0801

# Applications versions
app.key.googleMaps=AIzaSyBxJ39U2QIueuguBJxRX15DjniSZPyYi

# Build Properties
build.lint.abortOnError=false
build.lint.quiet=false
build.lint.ignoreWarnings=false
build.lint.warningAsErrors=false
# Gradle Properties
org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.vfs.watch=true

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
