org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true

app.signing.keyAlias=mizan_r
app.signing.keyPassword=Miz@n&&%%$$0801
app.signing.storePassword=Miz@n&&%%$$0801
app.version.code=2
app.version.name=1.1.0
app.version.suffix=
