org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
app.version.code=2
app.version.name=1.1.0
app.version.suffix=


android.useFullClasspathForDexingTransform=true
android.enableJetifier=true
android.defaults.buildfeatures.buildconfig=true
android.nonFinalResIds=false

# Applications versions
app.key.googleMaps=AIzaSyBxJ39U2QIueuguBJxRX15DjniSZPyYi
app.signing.keyAlias=btsmobile
app.signing.keyPassword=bt$mobile2023
app.signing.storePassword=bt$mobile2023

# Build Properties
build.lint.abortOnError=false
build.lint.quiet=false
build.lint.ignoreWarnings=false
build.lint.warningAsErrors=false
# Gradle Properties
org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.vfs.watch=true
